version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stapi-postgres
    restart: always
    environment:
      POSTGRES_DB: student_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
